### ISSUE TITLE
use makeExecutableSchema instead of GraphQLSchema

### ISSUE THREAD

**Issue by haxxorsid** [reactql/kit#131]
I want to use graphql-tools to define schema like this in src/graphql/schema.js:
```
const typeDefs = `
    type Message {
      message: String!
    }
`;

const resolvers = {
  Query: {
    message: () => [{message: getMessage()}],
  },
}

export default makeExecutableSchema({typeDefs, resolvers});
```
Refer: [graphql-tools](https://www.apollographql.com/docs/graphql-tools/generate-schema.html)
Instead of the default one which uses new GraphQLSchema() to declare schemas.

But in dev/browser.js & app.js, this is performed:
`config.setGraphQLSchema(require('src/graphql/schema').default);`

So how to integrate output of makeExecutableSchema?

**Comment by klarstrup** [comment]
Just write exactly what you wrote in `/graphql/schema`

**Comment by haxxorsid** [comment]
@klarstrup I didn't understood. What do you mean?

**Comment by klarstrup** [comment]
You're already doing what you need to, what's not working for you?

**Comment by haxxorsid** [comment]
I am receiving this error:
```
\node_modules\graphql\utilities\buildASTSchema.js:167
    throw new Error('Must provide schema definition with query type or a type named Query.');
Error: Must provide schema definition with query type or a type named Query.
    at Object.buildASTSchema (C:\Users\Admin\Desktop\gg\test\node_modules\graphql\utilities\buildASTSchema.js:167:11)
    at buildSchemaFromTypeDefinitions (C:\Users\Admin\Desktop\gg\test\node_modules\graphql-tools\dist\schemaGenerator.js:128:28)
    at _generateSchema (C:\Users\Admin\Desktop\gg\test\node_modules\graphql-tools\dist\schemaGenerator.js:48:18)
    at makeExecutableSchema (C:\Users\Admin\Desktop\gg\test\node_modules\graphql-tools\dist\schemaGenerator.js:64:20)
    at Object.<anonymous> (C:\Users\Admin\Desktop\gg\test\dist\server_dev.js:2367:60)
    at __webpack_require__ (C:\Users\Admin\Desktop\gg\test\dist\server_dev.js:20:30)
    at Object.defineProperty.value (C:\Users\Admin\Desktop\gg\test\dist\server_dev.js:1418:37)
    at __webpack_require__ (C:\Users\Admin\Desktop\gg\test\dist\server_dev.js:20:30)
    at Object.<anonymous> (C:\Users\Admin\Desktop\gg\test\dist\server_dev.js:870:12)
    at __webpack_require__ (C:\Users\Admin\Desktop\gg\test\dist\server_dev.js:20:30)

```

**Comment by leebenson** [comment]
It looks like you're missing a schema definition. From [this example](https://github.com/apollographql/graphql-tools#example):

```js
const typeDefs = `
type Author {
  id: ID! # the ! means that every author object _must_ have an id
  firstName: String
  lastName: String
  posts: [Post] # the list of Posts by this author
}

type Post {
  id: ID!
  title: String
  author: Author
  votes: Int
}

# the schema allows the following query:
type Query {
  posts: [Post]
}

# this schema allows the following mutation:
type Mutation {
  upvotePost (
    postId: ID!
  ): Post
}

# we need to tell the server which types represent the root query
# and root mutation types. We call them RootQuery and RootMutation by convention.
schema {   // <----- you're missing this
  query: Query
  mutation: Mutation
}
`;

export default typeDefs;
```

**Comment by ar1a** [comment]
I'm currently getting this, with this code:
```
// Schema for sample GraphQL server.

// ----------------------
// IMPORTS

import { makeExecutableSchema } from 'graphql-tools';

// ----------------------
const typeDefs = `
{
  type Query {
    message: String
  }

  schema {
    query: Query
  }
}
`;

const resolvers = {
  Query: {
    message() {
      return `Hello from GRAPHQL server at ${new Date()}!`;
    }
  }
};

export default makeExecutableSchema({
  typeDefs,
  resolvers
});

```
