### ISSUE TITLE
 Server breaks down even though it builds up successfully

### ISSUE THREAD

**Issue by Floridus** [reactql/kit#150]
Hello,

I need help, because I do not know what to do next. I have now successfully build and can run the server as well. But since I put the SSL_Port 443, it breaks off immediately after the successful construction again.

This is my build command in `package.json`

`cross-env NODE_ENV=production SSL_PORT=443 WEBPACK_CONFIG=browser_prod,server_prod webpack --colors`

Then i move the dist directory to my own webserver and execute the command npm run server.

`npm run server`

The answer looks like this:

```  
   ┌───────────────────────────────────────────────┐
   │                                               │
   │   Running server in production mode           │
   │                                               │
   │   - Local:            https://localhost       │
   │   - On Your Network:  https://xx.xx.xx.xx     │ <-- my change
   │                                               │
   └───────────────────────────────────────────────┘

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 0.0.0.0:443
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at Server.setupListenHandle [as _listen2] (net.js:1334:19)
    at listenInCluster (net.js:1392:12)
    at Server.listen (net.js:1476:7)
```

I do not know what I'm doing wrong? I have an SSL certificate on it and want to run it on the 443 port.

Or do I have to run a Docker image and then put this on my web server? Do not know me with Docker.

Thank you very much for any help.

**Comment by Floridus** [comment]
Okay, it was a mistake of mine. In the webserver nginx configuration just has to add that:

```
server {
    listen 80;
    server_name example.com;

    # this block here is new
    location / {
        proxy_set_header   X-Forwarded-For $remote_addr;
        proxy_set_header   Host $http_host;
        proxy_pass         http://localhost:4000;
    }
}
```
