### ISSUE TITLE
Won't start/build on windows

### ISSUE THREAD

**Issue by tsdexter** [reactql/kit#29]
I'm having an issue starting on windows - looks to me like it's not transpiling the .babel.js files but I'm new to webpack/babel. Do I need extra packages/config in node on windows to build it? **(edit: it starts/builds/runs fine in OSX with Node 7.10.0)**

```
> cross-env WEBPACK_CONFIG=browser_dev webpack-dev-server

C:\Users\tdexter\Documents\stuff\app\webpack.config.babel.js:11
import Config, { environment } from 'webpack-config';

^^^^^^
SyntaxError: Unexpected token import
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at module.exports (C:\Users\tdexter\AppData\Roaming\npm\node_modules\webpack\bin\convert-argv.js:80:13)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! app@0.0.1 start: `cross-env WEBPACK_CONFIG=browser_dev webpack-dev-server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the app@0.0.1 start script 'cross-env WEBPACK_CONFIG=browser_dev webpack-dev-server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env WEBPACK_CONFIG=browser_dev webpack-dev-server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls app 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\tdexter\AppData\Roaming\npm-cache\_logs\2017-05-23T14_53_03_280Z-debug.log
```

**Comment by tsdexter** [comment]
Hmm. I had to install everything in package.json manually to get it to build. Do you know if this is an issue with my setup or windows/npm in general? I did `npm install` first but I suppose it didn't work... This did though: 

```
npm install -s babel-core babel-eslint babel-loader babel-plugin-syntax-dynamic-import babel-plugin-transform-class-properties babel-plugin-transform-decorators-legacy babel-plugin-transform-object-rest-spread babel-plugin-transform-regenerator babel-polyfill babel-preset-env babel-preset-react babel-register chalk chunk-manifest-webpack-plugin compression-webpack-plugin copy-webpack-plugin cross-env css-loader cssnano eslint eslint-config-airbnb eslint-import-resolver-webpack eslint-plugin-babel eslint-plugin-compat eslint-plugin-import eslint-plugin-jsx-a11y eslint-plugin-react extract-text-webpack-plugin file-loader image-webpack-loader node-sass postcss-cssnext postcss-loader postcss-nested progress-bar-webpack-plugin resolve-url-loader rimraf sass-loader semantic-ui style-loader webpack webpack-bundle-analyzer webpack-chunk-hash webpack-config webpack-dev-server webpack-manifest-plugin webpack-node-externals isomorphic-fetch koa koa-helmet koa-router koa-static less less-loader microseconds prop-types react react-apollo react-dom react-helmet react-hot-loader react-redux react-router react-router-dom react-router-redux redux regenerator-runtime semantic-ui-css semantic-ui-react
```

**Comment by leebenson** [comment]
@tsdexter - how did you install the kit -- did you use the [CLI](https://github.com/reactql/cli)?

It runs yarn/npm for you, so you shouldn't need to run any installation commands.

**Comment by tsdexter** [comment]
@leebenson I used the CLI when I initiated the app on my MacBook, I did a bunch of work there and pushed everything to github then on my windows desktop I just cloned the repo from github and ran

```
npm install
npm start
```

Is there a CLI way to init an existing project that you've cloned? Or do you think my npm install just didn't install packages properly? 

Normally I include /node_modules in my repo as I've read horror stories about packages being unpublished. I'll do that for now for the rest of the team to clone it and get running easier.

**Comment by leebenson** [comment]
`npm install` should work, as long as `package.json` is in your repo.

There's also a `yarn.lock` file, for use with `yarn`. That's generally faster and safer.

**Comment by tsdexter** [comment]
That's what I figured. It must be an issue with my `npm install` which is
weird because it was a fresh installation of Node 7.10.0. Thanks for the
quick reply! And for the kit - it's perfect, I'm flying through this
project. 👍👍

**Comment by leebenson** [comment]
@tsdexter - my pleasure. Glad it's useful!

**Comment by tsdexter** [comment]
@leebenson I don't think it warrants an issue (maybe feature request?) but is there an easy way to build production without minification.. I'm getting an error on production thats not in dev and am having trouble tracking it down in the minified code... 

```
Error: Minified React error #130; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=130&args[]=undefined&args[]=%20Check%20the%20render%20method%20of%20%60t%60. for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at r (vendor.c2cf2f4….js:1)
    at i (vendor.c2cf2f4….js:1)
    at r (vendor.c2cf2f4….js:1)
    at o (vendor.c2cf2f4….js:1)
    at i (vendor.c2cf2f4….js:1)
    at Object.instantiateChildren (vendor.c2cf2f4….js:1)
    at h._reconcilerInstantiateChildren (vendor.c2cf2f4….js:1)
    at h.mountChildren (vendor.c2cf2f4….js:1)
    at h._createInitialChildren (vendor.c2cf2f4….js:1)
    at h.mountComponent (vendor.c2cf2f4….js:1)
```

Which may have to do with apollo? 

```
vendor.c2cf2f4….js:1 Unhandled (in react-apollo) Error: Network error: Minified React error #130; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=130&args[]=undefined&args[]=%20Check%20the%20render%20method%20of%20%60t%60. for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at new t (http://localhost:4000/vendor.c2cf2f40284a20946d16.js:1:510556)
    at r.currentResult (http://localhost:4000/vendor.c2cf2f40284a20946d16.js:1:691154)
    at v.dataForChild (http://localhost:4000/vendor.c2cf2f40284a20946d16.js:1:471311)
    at v.render (http://localhost:4000/vendor.c2cf2f40284a20946d16.js:1:471936)
    at f._renderValidatedComponentWithoutOwnerOrContext (http://localhost:4000/vendor.c2cf2f40284a20946d16.js:1:127561)
    at f._renderValidatedComponent (http://localhost:4000/vendor.c2cf2f40284a20946d16.js:1:127668)
    at f._updateRenderedComponent (http://localhost:4000/vendor.c2cf2f40284a20946d16.js:1:126992)
    at f._performComponentUpdate (http://localhost:4000/vendor.c2cf2f40284a20946d16.js:1:126793)
    at f.updateComponent (http://localhost:4000/vendor.c2cf2f40284a20946d16.js:1:126078)
    at f.receiveComponent (http://localhost:4000/vendor.c2cf2f40284a20946d16.js:1:125205)
```
React decoder: 

```
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. Check the render method of `t`
```
