### ISSUE TITLE
Docker build error

### ISSUE THREAD

**Issue by leebenson** [reactql/kit#56]
> reactql-app@2.0.0 server /src
> node dist/server
>
> fs.js:652
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

> Error: ENOENT: no such file or directory, open '/src/dist/manifest.json'
    at Object.fs.openSync (fs.js:652:18)
    at fs.readFileSync (fs.js:553:33)
    at __webpack_require__.map.name (/src/dist/server.js:577:110)
    at Array.map (native)
    at Object.<anonymous> (/src/dist/server.js:577:66)
    at __webpack_require__ (/src/dist/server.js:20:30)
    at Object.<anonymous> (/src/dist/server.js:513:18)
    at __webpack_require__ (/src/dist/server.js:20:30)
    at /src/dist/server.js:63:18
    at Object.<anonymous> (/src/dist/server.js:66:10)

**Comment by Bitti09** [comment]
@leebenson  can' reproduce the error  with todays repo state:
`> reactql-app@2.1.0 server /src
> node dist/server


   ┌────────────────────────────────────────────────┐
   │                                                │
   │   Running server in production mode            │
   │                                                │
   │   - Local:            http://x.x.x.x:4000      │
   │   - On Your Network:  http://y.y.y.y:4000   │
   │                                                │
   └────────────────────────────────────────────────┘

`

**Comment by leebenson** [comment]
thanks @Bitti09 - I fixed this in https://github.com/reactql/kit/commit/22f9b4a3210f3f2808083e2e76048fc784849891 - just forgot to close the issue 👍
